name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate Graph SVG
        run: |
          mkdir -p dist
          curl -s "https://github-readme-activity-graph.ashutoshh.workers.dev/graph?username=HelioASjunior&theme=tokyo-night&hide_border=true&bg_color=0d1117" -o dist/activity-graph.svg

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update activity graph"
          file_pattern: "dist/activity-graph.svg"
