name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ashutosh00710/github-readme-activity-graph@2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
